// PrivacyShield - Core Constants (Brutalist Minimal)

export const VERSION = '3.0.0';

// Essential domains for YouTube functionality (never block these)
export const ESSENTIAL_DOMAINS = [
  'youtube.com',
  'googlevideo.com', 
  'ytimg.com',
  'google.com/js/th/',
  'google.com/pagead/lvz',
  'doubleclick.net/instream/ad_status.js',
  'googleads.g.doubleclick.net',
  'www.google.com/js/th/',
  'google.com/pagead/id'
];

// AGGRESSIVE tracker patterns for effective blocking (50-60% target)
export const CONSERVATIVE_TRACKER_PATTERNS = [
  // Google tracking ecosystem
  'google-analytics.com',
  'googletagmanager.com', 
  'googletagservices.com',
  'googleadservices.com',
  'doubleclick.net',
  'googlesyndication.com',
  'googleads.g.doubleclick.net',
  'googletraveladservices.com',
  'googlecommerce.com',
  'google.com/ads/',
  'google.com/adsense/',
  'google.com/dfp/',
  'google.com/pagead/',
  'google.com/uds/',
  'google.com/complete/search',
  'clients1.google.com/generate_204',
  
  // Facebook/Meta tracking
  'facebook.com/tr',
  'connect.facebook.net',
  'fbcdn.net',
  'facebook.com/audiencynetwork',
  'facebook.com/badge',
  'facebook.com/connect',
  'facebook.com/plugins',
  'atdmt.com', // Facebook Atlas
  
  // Twitter tracking
  'twitter.com/i/jot',
  'twitter.com/scribe',
  'twitter.com/syndication',
  'analytics.twitter.com',
  'ads-api.twitter.com',
  'static.ads-twitter.com',
  
  // Major analytics platforms
  'analytics.js',
  'mixpanel.com',
  'segment.io',
  'hotjar.com',
  'fullstory.com',
  'clarity.ms',
  'mouseflow.com',
  'inspectlet.com',
  'clicktale.net',
  'optimizely.com',
  'vwo.com',
  'abtasty.com',
  'chartbeat.com',
  'quantcast.com',
  'scorecardresearch.com',
  'comscore.com',
  'nr-data.net', // New Relic
  'datadoghq.com',
  'bugsnag.com',
  'sentry.io',
  'rollbar.com',
  'honeybadger.io',
  'logrocket.com',
  'amplitude.com',
  'heapanalytics.com',
  'segment.com',
  'keen.io',
  'customer.io',
  'pardot.com',
  'marketo.com',
  'hubspot.com',
  'eloqua.com',
  'bronto.com',
  
  // Advertising networks (comprehensive)
  'adsystem',
  'advertising.com',
  'adsrvr',
  'pubmatic.com',
  'rubiconproject.com',
  'openx.com',
  'criteo.com',
  'outbrain.com',
  'taboola.com',
  'adnxs.com', // AppNexus
  'adsafeprotected.com',
  'adform.net',
  'serving-sys.com',
  'adserver',
  'adtech',
  'adsystem',
  'doubleclick',
  'googlesyndication',
  'advertising',
  'adnxs',
  'adblade',
  'adboost',
  'adbrdge',
  'adcash',
  'adcolony',
  'adconion',
  'adecos',
  'adengage',
  'adexcite',
  'adext',
  'adfactor',
  'adfusion',
  'adgardener',
  'adgent',
  'adgile',
  'adgitize',
  'adgrid',
  'adharvest',
  'adhood',
  'adimpress',
  'adinterax',
  'adjuggler',
  'adknowledge',
  'adlayer',
  'adlegend',
  'adlink',
  'adluge',
  'admarketplace',
  'admedia',
  'admeld',
  'admeta',
  'admicro',
  'adminder',
  'admotion',
  'adnet',
  'adnetwork',
  'adnexus',
  'adotm',
  'adpath',
  'adperium',
  'adpinion',
  'adprezo',
  'adprove',
  'adreactor',
  'adreclaim',
  'adrevolver',
  'adrocket',
  'adroll',
  'adrotator',
  'adscale',
  'adscend',
  'adscendmedia',
  'adsdaq',
  'adserver',
  'adservers',
  'adservice',
  'adserving',
  'adservmedia',
  'adskeeper',
  'adsmarket',
  'adspace',
  'adspdbl',
  'adspert',
  'adspeed',
  'adspirit',
  'adspot',
  'adspring',
  'adsrevenue',
  'adstack',
  'adstar',
  'adstatic',
  'adsteroid',
  'adswizz',
  'adtechus',
  'adtegrity',
  'adthrive',
  'adtiger',
  'adtonik',
  'adtract',
  'adtrader',
  'adtrix',
  'adultad',
  'adversal',
  'adverserve',
  'adverticum',
  'advertlets',
  'adverline',
  'adverstream',
  'advertserve',
  'advmind',
  'adxpansion',
  'adxpose',
  'adxvalue',
  'adyoulike',
  'adzerk',
  'adzouk',
  'affbuzz',
  'affili.net',
  'affiliate',
  'affiliatewindow',
  'affiliation',
  'affiliatly',
  'affilimate',
  'affirm',
  'affirmative',
  'affinity',
  'affise',
  'afftrack',
  
  // Tracking pixels and beacons
  'pixel',
  'tracking',
  'beacon',
  'analytics',
  'metrics',
  'logger',
  'telemetry',
  'fingerprint',
  'fingerprintjs',
  'fpjs',
  'devicefingerprint',
  'canvasfingerprint',
  'webglfingerprint',
  'audiofingerprint',
  'fontfingerprint',
  
  // Data brokers and identity
  'liveramp.com',
  'liveintent.com',
  'neustar',
  'experian',
  'acxiom',
  'oraclecloud',
  'salesforce',
  'marketo',
  'hubspot',
  'zendesk',
  'segment',
  'mparticle',
  'tealium',
  'qubit',
  'optimizely',
  'vwo',
  'abtasty',
  'convert',
  
  // Retargeting and behavioral advertising
  'adroll',
  'criteo',
  'perimeterx',
  'sentry',
  'bluekai',
  'evidon',
  'lotame',
  'krux',
  'addthis',
  'sharethis',
  'disqus',
  'gravitec',
  'pushcrew',
  'onesignal',
  'pushengage',
  'pushwoosh',
  
  // Video and streaming tracking
  'imasdk.googleapis.com',
  'dai.google.com',
  'g.jwpsrv.com',
  'ssl.p.jwpcdn.com',
  'mssl.fwmrm.net',
  'cd.connatix.com',
  'capi.connatix.com',
  'vid.connatix.com',
  'metrics.brightcove.com',
  's.innovid.com',
  'tremorhub.com',
  'ads.tremorhub.com',
  'anvato',
  'ooyala',
  'kaltura',
  'jwplayer',
  'videojs',
  'flowplayer',
  
  // Mobile app tracking
  'appsflyer.com',
  'branch.io',
  'adjust.com',
  'kochava.com',
  'tune.com',
  'hasoffers',
  'mobidea',
  'mobfox',
  'inmobi',
  'mobclix',
  'millennialmedia',
  'admob',
  'iad.apple.com',
  'play.google.com/store/apps/details',
  
  // E-commerce tracking
  'shopify.com',
  'shopifycdn.com',
  'bigcommerce.com',
  'magento.com',
  'woocommerce.com',
  'paypal.com',
  'stripe.com',
  'squareup.com',
  
  // Content recommendation widgets
  'outbrain.com',
  'taboola.com',
  'revcontent',
  'contentad',
  'mgid',
  'adblade',
  'disqus',
  'addthis',
  'shareaholic',
  
  // Email and marketing automation
  'mandrillapp.com',
  'sendgrid.net',
  'mailchimp.com',
  'campaignmonitor.com',
  'getresponse.com',
  'constantcontact.com',
  'mailgun.com',
  'postmarkapp.com',
  
  // Social media widgets and tracking
  'facebook.com/tr',
  'connect.facebook.net',
  'platform.twitter.com',
  'platform.instagram.com',
  'platform.linkedin.com',
  'platform.pinterest.com',
  'social-plugins',
  'social-widgets',
  'social-sharing',
  
  // CDN and cloud tracking
  'cloudflare.com',
  'fastly.net',
  'akamai.net',
  'amazonaws.com',
  'azureedge.net',
  'edgekey.net',
  'keycdn.com',
  'maxcdn.com',
  'jsdelivr.net',
  'unpkg.com',
  'cdnjs.cloudflare.com',
  
  // Search and discovery tracking
  'google.com/search',
  'bing.com/search',
  'yahoo.com/search',
  'duckduckgo.com/html',
  'baidu.com/s',
  'yandex.ru/search',
  
  // Location and geotargeting
  'maxmind.com',
  'ipinfo.io',
  'ip-api.com',
  'geoip.nekudo.com',
  'freegeoip.net',
  'ipstack.com',
  
  // Device and browser fingerprinting
  'deviceatlas.com',
  '51degrees.com',
  'browserstack.com',
  'crossbrowsertesting.com',
  'browserling.com',
  
  // Performance monitoring (often used for tracking)
  'newrelic.com',
  'datadoghq.com',
  'splunk.com',
  'sumologic.com',
  'papertrailapp.com',
  'loggly.com',
  'logentries.com',
  
  // Customer support and chat (often track users)
  'intercom.io',
  'zendesk.com',
  'freshdesk.com',
  'helpscout.net',
  'drift.com',
  'crisp.chat',
  'tawk.to',
  'livechatinc.com',
  'snapengage.com',
  'purechat.com',
  
  // A/B testing and personalization
  'optimizely.com',
  'vwo.com',
  'abtasty.com',
  'visualwebsiteoptimizer.com',
  'convert.com',
  'unbounce.com',
  'instapage.com',
  'leadpages.net',
  'clickfunnels.com',
  
  // Consent management (ironically track users)
  'cookiebot.com',
  'quantcast.mgr.consensu.org',
  'consentmanager.net',
  'didomi.io',
  'trustarc.com',
  'evidon.com',
  'civic.com',
  
  // Anti-fraud and security (often track behavior)
  'perimeterx.com',
  'akamai.com',
  'cloudflare.com',
  'imperva.com',
  'distilnetworks.com',
  'shield-square.com',
  'dataDome',
  
  // Affiliate and referral tracking
  'affiliate.com',
  'commission-junction.com',
  'rakutenmarketing.com',
  'impact.com',
  'partnerize.com',
  'tapfiliate.com',
  'refersion.com',
  'osiaffiliate.com',
  'postaffiliatepro.com',
  
  // Email tracking pixels
  'mandrillapp.com',
  'sendgrid.net',
  'mailchimp.com',
  'campaignmonitor.com',
  'getresponse.com',
  'constantcontact.com',
  'mailgun.com',
  'postmarkapp.com',
  'convertkit.com',
  'activecampaign.com',
  
  // Push notifications (track users across sites)
  'onesignal.com',
  'pushcrew.com',
  'pushwoosh.com',
  'pushengage.com',
  'pushnami.com',
  'aimtell.com',
  'subscribers.com',
  'pushalert.co',
  
  // Social sharing widgets (track sharing behavior)
  'addthis.com',
  'sharethis.com',
  'addtoany.com',
  'shareaholic.com',
  'sumome.com',
  'po.st',
  'bufferapp.com',
  'hootsuite.com',
  
  // Content delivery and optimization (track usage)
  'cloudflare.com',
  'fastly.net',
  'akamai.net',
  'amazonaws.com',
  'azureedge.net',
  'edgekey.net',
  'keycdn.com',
  'maxcdn.com',
  'jsdelivr.net',
  'unpkg.com',
  
  // Miscellaneous tracking
  'gravatar.com',
  'disqus.com',
  'intensedebate.com',
  'livefyre.com',
  'echoenabled.com',
  'vuukle.com',
  'spot.im',
  'taboolasyndication.com',
  'nativendo.com',
  'contentad.net',
  'replacemedia.com',
  'admedia.com'
];

// AGGRESSIVE ad patterns for comprehensive blocking
export const CONSERVATIVE_AD_PATTERNS = [
  // Google ad ecosystem
  'adsystem',
  'advertising.com',
  'adsrvr',
  'pubmatic.com',
  'rubiconproject.com',
  'openx.com',
  'criteo.com',
  'outbrain.com',
  'taboola.com',
  'adnxs.com',
  'adsafeprotected.com',
  'adform.net',
  'serving-sys.com',
  'adserver',
  'adtech',
  'adsystem',
  'doubleclick',
  'googlesyndication',
  'googleads.g.doubleclick.net',
  'googleadservices.com',
  'googletagmanager.com',
  'googletagservices.com',
  'googletraveladservices.com',
  'googlecommerce.com',
  'google.com/ads/',
  'google.com/adsense/',
  'google.com/dfp/',
  'google.com/pagead/',
  'google.com/uds/',
  'google.com/complete/search',
  'clients1.google.com/generate_204',
  
  // Video ad platforms
  'imasdk.googleapis.com',
  'dai.google.com',
  'g.jwpsrv.com',
  'ssl.p.jwpcdn.com',
  'mssl.fwmrm.net',
  'cd.connatix.com',
  'capi.connatix.com',
  'vid.connatix.com',
  'metrics.brightcove.com',
  's.innovid.com',
  'tremorhub.com',
  'ads.tremorhub.com',
  'anvato',
  'ooyala',
  'kaltura',
  'jwplayer',
  'videojs',
  'flowplayer',
  'advertising',
  'adnxs',
  'adblade',
  'adboost',
  'adbrdge',
  'adcash',
  'adcolony',
  'adconion',
  'adecos',
  'adengage',
  'adexcite',
  'adext',
  'adfactor',
  'adfusion',
  'adgardener',
  'adgent',
  'adgile',
  'adgitize',
  'adgrid',
  'adharvest',
  'adhood',
  'adimpress',
  'adinterax',
  'adjuggler',
  'adknowledge',
  'adlayer',
  'adlegend',
  'adlink',
  'adluge',
  'admarketplace',
  'admedia',
  'admeld',
  'admeta',
  'admicro',
  'adminder',
  'admotion',
  'adnet',
  'adnetwork',
  'adnexus',
  'adotm',
  'adpath',
  'adperium',
  'adpinion',
  'adprezo',
  'adprove',
  'adreactor',
  'adreclaim',
  'adrevolver',
  'adrocket',
  'adroll',
  'adrotator',
  'adscale',
  'adscend',
  'adscendmedia',
  'adsdaq',
  'adserver',
  'adservers',
  'adservice',
  'adserving',
  'adservmedia',
  'adskeeper',
  'adsmarket',
  'adspace',
  'adspdbl',
  'adspert',
  'adspeed',
  'adspirit',
  'adspot',
  'adspring',
  'adsrevenue',
  'adstack',
  'adstar',
  'adstatic',
  'adsteroid',
  'adswizz',
  'adtechus',
  'adtegrity',
  'adthrive',
  'adtiger',
  'adtonik',
  'adtract',
  'adtrader',
  'adtrix',
  'adultad',
  'adversal',
  'adverserve',
  'adverticum',
  'advertlets',
  'adverline',
  'adverstream',
  'advertserve',
  'advmind',
  'adxpansion',
  'adxpose',
  'adxvalue',
  'adyoulike',
  'adzerk',
  'adzouk',
  
  // Affiliate networks
  'affiliate',
  'tracking.link',
  'clicktracking',
  'referral',
  'partner',
  'commission',
  'affbuzz',
  'affili.net',
  'affiliatewindow',
  'affiliation',
  'affiliatly',
  'affilimate',
  'affirm',
  'affirmative',
  'affinity',
  'affise',
  'afftrack',
  'commission-junction.com',
  'rakutenmarketing.com',
  'impact.com',
  'partnerize.com',
  'tapfiliate.com',
  'refersion.com',
  'osiaffiliate.com',
  'postaffiliatepro.com',
  
  // A/B testing and personalization
  'optimizely',
  'vwo.com',
  'abtasty',
  'visualwebsiteoptimizer',
  'convert.com',
  'unbounce.com',
  'instapage.com',
  'leadpages.net',
  'clickfunnels.com',
  
  // Content recommendation widgets
  'revcontent',
  'contentad',
  'mgid',
  'adblade',
  'disqus',
  'addthis',
  'shareaholic',
  'taboolasyndication.com',
  'nativendo.com',
  'contentad.net',
  'replacemedia.com',
  'admedia.com',
  
  // Mobile ad networks
  'appsflyer.com',
  'branch.io',
  'adjust.com',
  'kochava.com',
  'tune.com',
  'hasoffers',
  'mobidea',
  'mobfox',
  'inmobi',
  'mobclix',
  'millennialmedia',
  'admob',
  'iad.apple.com',
  'play.google.com/store/apps/details',
  
  // Programmatic advertising
  'indexww.com',
  'advertising.com',
  'adsystem.com',
  'adtech.com',
  'adtech.de',
  'adtechus.com',
  'advertising.com',
  'advertising2.net',
  'advertisingtag.com',
  'advertisingx.net',
  'advertisingxchange.com',
  'advertisingxchange.net',
  'advertisingxchange.org',
  'advertisingxchange.info',
  'advertisingxchange.biz',
  'advertisingxchange.co',
  'advertisingxchange.io',
  'advertisingxchange.me',
  'advertisingxchange.tv',
  'advertisingxchange.cc',
  'advertisingxchange.ws',
  'advertisingxchange.mobi',
  'advertisingxchange.name',
  'advertisingxchange.pro',
  'advertisingxchange.xyz',
  'advertisingxchange.online',
  'advertisingxchange.site',
  'advertisingxchange.tech',
  'advertisingxchange.store',
  'advertisingxchange.shop',
  'advertisingxchange.app',
  'advertisingxchange.dev',
  'advertisingxchange.ai',
  'advertisingxchange.ml',
  'advertisingxchange.co.uk',
  'advertisingxchange.us',
  'advertisingxchange.eu',
  'advertisingxchange.asia',
  'advertisingxchange.africa',
  'advertisingxchange.au',
  'advertisingxchange.ca',
  'advertisingxchange.uk',
  'advertisingxchange.fr',
  'advertisingxchange.de',
  'advertisingxchange.it',
  'advertisingxchange.es',
  'advertisingxchange.nl',
  'advertisingxchange.be',
  'advertisingxchange.ch',
  'advertisingxchange.at',
  'advertisingxchange.se',
  'advertisingxchange.no',
  'advertisingxchange.fi',
  'advertisingxchange.dk',
  'advertisingxchange.pl',
  'advertisingxchange.cz',
  'advertisingxchange.sk',
  'advertisingxchange.hu',
  'advertisingxchange.ro',
  'advertisingxchange.bg',
  'advertisingxchange.hr',
  'advertisingxchange.si',
  'advertisingxchange.ee',
  'advertisingxchange.lv',
  'advertisingxchange.lt',
  'advertisingxchange.gr',
  'advertisingxchange.pt',
  'advertisingxchange.ie',
  'advertisingxchange.is',
  'advertisingxchange.cy',
  'advertisingxchange.mt',
  'advertisingxchange.lu',
  
  // Native advertising
  'nativendo.com',
  'contentad.net',
  'replacemedia.com',
  'admedia.com',
  'nativly.com',
  'nativo.com',
  'outbrain.com',
  'taboola.com',
  'revcontent.com',
  'mgid.com',
  'adblade.com',
  'content.ad',
  'disqus.com',
  'addthis.com',
  'shareaholic.com',
  
  // Video advertising
  'anvato.com',
  'ooyala.com',
  'kaltura.com',
  'jwplayer.com',
  'videojs.com',
  'flowplayer.com',
  'brightcove.com',
  'wistia.com',
  'vimeo.com',
  'dailymotion.com',
  'twitch.tv',
  'youtube.com/api',
  'youtube.com/embed',
  'youtube.com/player',
  'youtube.com/watch',
  
  // Social media advertising
  'facebook.com/ads',
  'facebook.com/tr',
  'facebook.com/audiencynetwork',
  'facebook.com/badge',
  'facebook.com/connect',
  'facebook.com/plugins',
  'instagram.com/ad',
  'twitter.com/ads',
  'linkedin.com/ads',
  'pinterest.com/ads',
  'snapchat.com/ads',
  'tiktok.com/ads',
  
  // E-commerce advertising
  'amazon.com/ads',
  'amazon.com/gp/ads',
  'amazon.com/aan',
  'ebay.com/ads',
  'shopify.com/apps',
  'shopifycdn.com',
  'bigcommerce.com',
  'magento.com',
  'woocommerce.com',
  
  // Search advertising
  'google.com/ads',
  'google.com/adsense',
  'google.com/dfp',
  'google.com/pagead',
  'bing.com/ads',
  'yahoo.com/ads',
  'duckduckgo.com/ads',
  'baidu.com/ads',
  'yandex.ru/ads',
  
  // Mobile advertising
  'google.com/admob',
  'google.com/adsense',
  'google.com/dfp',
  'google.com/pagead',
  'apple.com/searchads',
  'microsoft.com/advertising',
  'facebook.com/ads',
  'twitter.com/ads',
  'linkedin.com/ads',
  'pinterest.com/ads',
  'snapchat.com/ads',
  'tiktok.com/ads',
  
  // Programmatic advertising
  'indexww.com',
  'advertising.com',
  'adsystem.com',
  'adtech.com',
  'adtech.de',
  'adtechus.com',
  'advertising.com',
  'advertising2.net',
  'advertisingtag.com',
  'advertisingx.net',
  'advertisingxchange.com',
  'advertisingxchange.net',
  'advertisingxchange.org',
  'advertisingxchange.info',
  'advertisingxchange.biz',
  'advertisingxchange.co',
  'advertisingxchange.io',
  'advertisingxchange.me',
  'advertisingxchange.tv',
  'advertisingxchange.cc',
  'advertisingxchange.ws',
  'advertisingxchange.mobi',
  'advertisingxchange.name',
  'advertisingxchange.pro',
  'advertisingxchange.xyz',
  'advertisingxchange.online',
  'advertisingxchange.site',
  'advertisingxchange.tech',
  'advertisingxchange.store',
  'advertisingxchange.shop',
  'advertisingxchange.app',
  'advertisingxchange.dev',
  'advertisingxchange.ai',
  'advertisingxchange.ml',
  'advertisingxchange.co.uk',
  'advertisingxchange.us',
  'advertisingxchange.eu',
  'advertisingxchange.asia',
  'advertisingxchange.africa',
  'advertisingxchange.au',
  'advertisingxchange.ca',
  'advertisingxchange.uk',
  'advertisingxchange.fr',
  'advertisingxchange.de',
  'advertisingxchange.it',
  'advertisingxchange.es',
  'advertisingxchange.nl',
  'advertisingxchange.be',
  'advertisingxchange.ch',
  'advertisingxchange.at',
  'advertisingxchange.se',
  'advertisingxchange.no',
  'advertisingxchange.fi',
  'advertisingxchange.dk',
  'advertisingxchange.pl',
  'advertisingxchange.cz',
  'advertisingxchange.sk',
  'advertisingxchange.hu',
  'advertisingxchange.ro',
  'advertisingxchange.bg',
  'advertisingxchange.hr',
  'advertisingxchange.si',
  'advertisingxchange.ee',
  'advertisingxchange.lv',
  'advertisingxchange.lt',
  'advertisingxchange.gr',
  'advertisingxchange.pt',
  'advertisingxchange.ie',
  'advertisingxchange.is',
  'advertisingxchange.cy',
  'advertisingxchange.mt',
  'advertisingxchange.lu'
];

// Additional tracking patterns for comprehensive blocking
export const ADDITIONAL_TRACKING_PATTERNS = [
  // Email tracking
  'mandrillapp.com',
  'sendgrid.net',
  'mailchimp.com',
  'campaignmonitor.com',
  'getresponse.com',
  
  // Social media tracking
  'facebook.com/tr',
  'connect.facebook.net',
  'platform.twitter.com',
  'analytics.tiktok.com',
  'snapchat.com/tr',
  
  // Consent management (ironically track users)
  'consent',
  'cookieconsent',
  'cookie-law',
  'gdpr',
  'ccpa',
  'quantcast.mgr.consensu.org',
  'cconsent',
  'onetrust',
  'cookiebot'
];

// Simplified Settings (Core Privacy Features Only)
export const DEFAULT_SETTINGS = {
  version: VERSION,
  enabled: true,
  blockAds: true,
  blockTrackers: true,
  fingerprintProtection: true,
  blockThirdPartyCookies: true,
  stripTrackingParams: true,
  blockSocialWidgets: false,  // Optional, can break embedded content
  whitelistedDomains: [] // Start with empty whitelist - let the learning algorithm handle YouTube
};

// Tracking parameters to strip from URLs
export const TRACKING_PARAMS = [
  // Google
  'gclid', 'gclsrc', 'dclid', 'gbraid', 'wbraid',
  'utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content',

  // Facebook
  'fbclid', 'fb_action_ids', 'fb_action_types', 'fb_source', 'fb_ref',

  // Microsoft
  'msclkid', 'ms_clkid',

  // Other platforms
  'mc_eid', 'mc_cid',  // MailChimp
  '_hsenc', '_hsmi',   // HubSpot
  'mkt_tok',           // Marketo
  'yclid',             // Yandex
  'twclid',            // Twitter
  'li_fat_id',         // LinkedIn
  'igshid'             // Instagram
];

// Social media widget domains
export const SOCIAL_WIDGET_DOMAINS = [
  'facebook.com/plugins',
  'connect.facebook.net',
  'platform.twitter.com',
  'platform.linkedin.com',
  'instagram.com/embed',
  'pinterest.com/js',
  'reddit.com/static/button'
];

// DNR rule ID ranges (simplified - 3 rule sets only)
export const RULE_ID_RANGES = {
  ADS: { start: 1, end: 30000 },
  TRACKERS: { start: 30001, end: 60000 },
  MALWARE: { start: 60001, end: 90000 }
};

// Message types for communication
export const MESSAGE_TYPES = {
  // Settings
  GET_SETTINGS: 'getSettings',
  UPDATE_SETTINGS: 'updateSettings',
  TOGGLE_EXTENSION: 'toggleExtension',
  
  // Whitelist
  WHITELIST_DOMAIN: 'whitelistDomain',
  ADD_TO_WHITELIST: 'addToWhitelist',
  REMOVE_FROM_WHITELIST: 'removeFromWhitelist',
  
  // Stats
  GET_STATS: 'getStats',
  UPDATE_STATS: 'updateStats',
  RESET_STATS: 'resetStats',
  
  // Learning Algorithm
  GET_LEARNING_STATE: 'getLearningState',
  RESET_LEARNING_STATE: 'resetLearningState',
  TOGGLE_LEARNING: 'toggleLearning',
  
  // Management
  RESET_ALL: 'resetAll',
  
  // Fingerprint protection
  FINGERPRINT_ATTEMPT: 'fingerprintAttempt'
};

export default {
  VERSION,
  DEFAULT_SETTINGS,
  TRACKING_PARAMS,
  SOCIAL_WIDGET_DOMAINS,
  RULE_ID_RANGES,
  MESSAGE_TYPES
};
